package com.metacube.helpdesk.model;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

import com.metacube.helpdesk.utility.Designation;

@Entity
@Table(name = "Employee")
public class Employee implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    // Autogenerated employeeId
    @Id
    @Column(name = "employeeId")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int employeeId;

    // defines table attribute employeeName
    @Column(name = "employeeName", nullable = false)
    private String employeeName;

    @Enumerated(EnumType.STRING)
    private Designation designation;

    // defines table attribute contactNumber
    @Column(name = "contactNumber", nullable = false)
    private String contactNumber;

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + employeeId;
        result = prime * result
                + ((username == null) ? 0 : username.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Employee other = (Employee) obj;
        if (employeeId != other.employeeId)
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        } else if (!username.equals(other.username))
            return false;
        return true;
    }

    // defines status of the employee
    @Column(name = "status", nullable = false)
    private String status;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "username", referencedColumnName = "username", unique = true, nullable = false)
    private LogIn username;

    @ManyToOne
    @JoinColumn(name = "orgId", nullable = false)
    private Organisation organisation;
    
    
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
        name = "Employee_Team", 
        joinColumns = { @JoinColumn(name = "employeeId") }, 
        inverseJoinColumns = { @JoinColumn(name = "teamId") }
    )
    Set<Team> teams = new HashSet<Team>();
    
    
    
    public Employee(int employeeId, String employeeName,
			Designation designation, String contactNumber, String status,
			LogIn username, Organisation organisation, Set<Team> teams) {
		this.employeeId = employeeId;
		this.employeeName = employeeName;
		this.designation = designation;
		this.contactNumber = contactNumber;
		this.status = status;
		this.username = username;
		this.organisation = organisation;
		this.teams = teams;
	}

	public Designation getDesignation() {
		return designation;
	}

	public void setDesignation(Designation designation) {
		this.designation = designation;
	}

	public Set<Team> getTeams() {
        return teams;
    }

    public void setTeams(Set<Team> teams) {
        this.teams = teams;
    }

    public Employee() {

    }

    public int getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    public String getEmployeeName() {
        return employeeName;
    }

    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName;
    }

  

    public String getContactNumber() {
        return contactNumber;
    }

    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LogIn getUsername() {
        return username;
    }

    public void setUsername(LogIn username) {
        this.username = username;
    }

    public Organisation getOrganisation() {
        return organisation;
    }

    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }
}
