package com.metacube.helpdesk.model;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name="Team")
public class Team implements Serializable {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /*
     *Autogenerated teamId
     *mapped with database table Team column teamId 
     */
    @Id
    @Column(name="teamId")
    @GeneratedValue(strategy= GenerationType.AUTO)
    private int teamId;
    
    @Column(name="teamName", nullable = false)
    private String teamName;
    
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="orgId",nullable=false)
    private Organisation organisation;
    
    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name="teamHead")
    private Employee teamHead;
    

    public Team() {

    }

    public Team(String teamName, Organisation organisation, Employee teamHead) {
 
        this.teamName = teamName;
        this.organisation = organisation;
        this.teamHead = teamHead;
    }

    public int getTeamId() {
        return teamId;
    }

    public void setTeamId(int teamId) {
        this.teamId = teamId;
    }

    public String getTeamName() {
        return teamName;
    }

    public void setTeamName(String teamName) {
        this.teamName = teamName;
    }

    public Organisation getOrganisation() {
        return organisation;
    }

    public void setOrganisation(Organisation organisation) {
        this.organisation = organisation;
    }

    public Employee getTeamHead() {
        return teamHead;
    }

    public void setTeamHead(Employee teamHead) {
        this.teamHead = teamHead;
    }
    
    
}
