package com.metacube.helpdesk.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "Ticket")
public class Ticket implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    // Autogenerated employeeId
    @Id
    @Column(name = "ticketNo")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int ticketNo;

    // doubtful case ( two joins on same column)
    @ManyToOne
    @JoinColumn(name = "requester", nullable = false)
    private Employee requester;

    @ManyToOne
    @JoinColumn(name = "requestedFor", nullable = false)
    private Employee requestedFor;

    @Column(name = "requestDate", nullable = false)
    private Date requestDate;
    
    @Column(name = "location")
    private String location;

    public Ticket(int ticketNo, Employee requester, Employee requestedFor,
            Date requestDate, String location, String requestType,
            String priority, String status, String comment,
            ItResource requestedResource) {

        this.ticketNo = ticketNo;
        this.requester = requester;
        this.requestedFor = requestedFor;
        this.requestDate = requestDate;
        this.location = location;
        this.requestType = requestType;
        this.priority = priority;
        this.status = status;
        this.comment = comment;
        this.requestedResource = requestedResource;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    // to be made enum
    @Column(name = "requestType", nullable = false)
    private String requestType;

    // to be made enum
    @Column(name = "priority", nullable = false)
    private String priority;

    // to be made enum
    @Column(name = "status", nullable = false)
    private String status;

    @Column(name = "comment")
    private String comment;

    @ManyToOne
    @JoinColumn(name = "requestedResource", nullable = false)
    private ItResource requestedResource;

    public Ticket() {

    }

    public ItResource getRequestedResource() {
        return requestedResource;
    }

    public void setRequestedResource(ItResource requestedResource) {
        this.requestedResource = requestedResource;
    }

    public int getTicketNo() {
        return ticketNo;
    }

    public void setTicketNo(int ticketNo) {
        this.ticketNo = ticketNo;
    }

    public Employee getRequester() {
        return requester;
    }

    public void setRequester(Employee requester) {
        this.requester = requester;
    }

    public Employee getRequestedFor() {
        return requestedFor;
    }

    public void setRequestedFor(Employee requestedFor) {
        this.requestedFor = requestedFor;
    }

    public Date getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Ticket(Employee requester, Employee requestedFor, Date requestDate,
            String requestType, String priority, String status, String comment,
            ItResource requestedResource) {

        this.requester = requester;
        this.requestedFor = requestedFor;
        this.requestDate = requestDate;
        this.requestType = requestType;
        this.priority = priority;
        this.status = status;
        this.comment = comment;
        this.requestedResource = requestedResource;
    }

}
