package com.metacube.helpdesk.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@Table(name = "Ticket")
public class Ticket implements Serializable {

    private static final long serialVersionUID = 1L;
    // Autogenerated employeeId
    @Id
    @Column(name = "ticketNo")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int ticketNo;
    // doubtful case ( two joins on same column)
    @ManyToOne
    @JoinColumn(name = "requester", nullable = false)
    private Employee requester;
    @ManyToOne
    @JoinColumn(name = "requestedFor", nullable = false)
    private Employee requestedFor;
    @ManyToOne
    @JoinColumn(name = "correspondingTeam", nullable = false)
    private Team correspondingTeam;
    @Column(name = "requestDate")
    private Date requestDate;
    @Column(name = "seatLocation")
    private String seatLocation;
    // to be made enum
    @Column(name = "requestType", nullable = false)
    private String requestType;
    // to be made enum
    @Column(name = "priority", nullable = false)
    private String priority;
    // to be made enum
    @Column(name = "status", nullable = false)
    private String status;
    @Column(name = "comment")
    private String comment;
    @ManyToOne
    @JoinColumn(name = "requestedResource", nullable = false)
    private ItResource requestedResource;
    @Column(name = "lastDateOfUpdate", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date lastDateOfUpdate;
    @Column(name = "lastUpdatedBy", nullable = false)
    private String lastUpdatedBy;

    public Team getCorrespondingTeam() {
        return correspondingTeam;
    }

    public void setCorrespondingTeam(Team correspondingTeam) {
        this.correspondingTeam = correspondingTeam;
    }

    public Date getLastDateOfUpdate() {
        return lastDateOfUpdate;
    }

    public void setLastDateOfUpdate(Date lastDateOfUpdate) {
        this.lastDateOfUpdate = lastDateOfUpdate;
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    @PrePersist
    protected void onCreate() {
        this.lastDateOfUpdate = this.requestDate = new Date();
    }

    @PreUpdate
    protected void onUpdate() {
        this.lastDateOfUpdate = new Date();
    }

    public Ticket() {
    }

    public Ticket( int ticketNo, Employee requester, Employee requestedFor,
            Team correspondingTeam, Date requestDate, String seatLocation,
            String requestType, String priority, String status, String comment,
            ItResource requestedResource, Date lastDateOfUpdate,
            String lastUpdatedBy ) {
        this.ticketNo = ticketNo;
        this.requester = requester;
        this.requestedFor = requestedFor;
        this.correspondingTeam = correspondingTeam;
        this.requestDate = requestDate;
        this.seatLocation = seatLocation;
        this.requestType = requestType;
        this.priority = priority;
        this.status = status;
        this.comment = comment;
        this.requestedResource = requestedResource;
        this.lastDateOfUpdate = lastDateOfUpdate;
        this.lastUpdatedBy = lastUpdatedBy;
    }

    public String getSeatLocation() {
        return seatLocation;
    }

    public void setSeatLocation(String seatLocation) {
        this.seatLocation = seatLocation;
    }

    public ItResource getRequestedResource() {
        return requestedResource;
    }

    public void setRequestedResource(ItResource requestedResource) {
        this.requestedResource = requestedResource;
    }

    public int getTicketNo() {
        return ticketNo;
    }

    public void setTicketNo(int ticketNo) {
        this.ticketNo = ticketNo;
    }

    public Employee getRequester() {
        return requester;
    }

    public void setRequester(Employee requester) {
        this.requester = requester;
    }

    public Employee getRequestedFor() {
        return requestedFor;
    }

    public void setRequestedFor(Employee requestedFor) {
        this.requestedFor = requestedFor;
    }

    public Date getRequestDate() {
        return requestDate;
    }

    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public String getRequestType() {
        return requestType;
    }

    public void setRequestType(String requestType) {
        this.requestType = requestType;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}
