package com.metacube.helpdesk.modal;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name="Employee")
public class Employee {
	
	//Autogenerated employeeId
	@Id
	@Column(name="employeeId")
	@GeneratedValue(strategy= GenerationType.AUTO)
	private int employeeId;
	
	//defines table attribute employeeName
	@Column(name="employeeName")
	private String employeeName;
	
	//defines table attribute contactNumber
	@Column(name="contactNumber")
	private String contactNumber;
	
	//defines status of the employee
	@Column(name="status")
	private String status;
	
	/*
	 * many to one mapping
	 * 
	 */
	@ManyToOne(cascade = CascadeType.ALL)
	private Employee reportingManager;
	
	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name="orgID")
	private Organisation organisation;
	
	public Employee() {
		
	}

	public Employee(String employeeName, String contactNumber, String status,
			 Employee reportingManager, Organisation organisation) {
		
		this.employeeName = employeeName;
		this.contactNumber = contactNumber;
		this.status = status;
		this.reportingManager = reportingManager;
		this.organisation = organisation;
	}

	public int getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public String getEmployeeName() {
		return employeeName;
	}

	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	public String getContactNumber() {
		return contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	
	public Employee getReportingManager() {
		return reportingManager;
	}

	public void setReportingManager(Employee reportingManager) {
		this.reportingManager = reportingManager;
	}

	public Organisation getOrganisation() {
		return organisation;
	}

	public void setOrganisation(Organisation organisation) {
		this.organisation = organisation;
	}

	
}
